/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/WurzelWorkspace/src/rvc_utils/msg/DataSetMessage.msg
 *
 */


#ifndef RVC_UTILS_MESSAGE_DATASETMESSAGE_H
#define RVC_UTILS_MESSAGE_DATASETMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rvc_utils
{
template <class ContainerAllocator>
struct DataSetMessage_
{
  typedef DataSetMessage_<ContainerAllocator> Type;

  DataSetMessage_()
    : header()
    , dataset_name()
    , dataset_idx(0)  {
    }
  DataSetMessage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , dataset_name(_alloc)
    , dataset_idx(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dataset_name_type;
  _dataset_name_type dataset_name;

   typedef uint8_t _dataset_idx_type;
  _dataset_idx_type dataset_idx;




  typedef boost::shared_ptr< ::rvc_utils::DataSetMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rvc_utils::DataSetMessage_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct DataSetMessage_

typedef ::rvc_utils::DataSetMessage_<std::allocator<void> > DataSetMessage;

typedef boost::shared_ptr< ::rvc_utils::DataSetMessage > DataSetMessagePtr;
typedef boost::shared_ptr< ::rvc_utils::DataSetMessage const> DataSetMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rvc_utils::DataSetMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rvc_utils::DataSetMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rvc_utils

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg'], 'rvc_utils': ['/home/viki/WurzelWorkspace/src/rvc_utils/msg'], 'geometry_msgs': ['/opt/ros/groovy/share/geometry_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rvc_utils::DataSetMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rvc_utils::DataSetMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rvc_utils::DataSetMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rvc_utils::DataSetMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rvc_utils::DataSetMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rvc_utils::DataSetMessage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rvc_utils::DataSetMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59c0368b3e65867e9b2926656b1c15a9";
  }

  static const char* value(const ::rvc_utils::DataSetMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59c0368b3e65867eULL;
  static const uint64_t static_value2 = 0x9b2926656b1c15a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rvc_utils::DataSetMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rvc_utils/DataSetMessage";
  }

  static const char* value(const ::rvc_utils::DataSetMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rvc_utils::DataSetMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
# Name of the data set, i.e. one of: graffiti, boat, bikes \n\
string dataset_name\n\
\n\
# index of the image in the dataset from which the destination points originate\n\
uint8 dataset_idx\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const ::rvc_utils::DataSetMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rvc_utils::DataSetMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.dataset_name);
      stream.next(m.dataset_idx);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DataSetMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rvc_utils::DataSetMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rvc_utils::DataSetMessage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dataset_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dataset_name);
    s << indent << "dataset_idx: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dataset_idx);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RVC_UTILS_MESSAGE_DATASETMESSAGE_H
