/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/WurzelWorkspace/src/rvc_utils/msg/ROCCurveMessage.msg
 *
 */


#ifndef RVC_UTILS_MESSAGE_ROCCURVEMESSAGE_H
#define RVC_UTILS_MESSAGE_ROCCURVEMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Point32.h>

namespace rvc_utils
{
template <class ContainerAllocator>
struct ROCCurveMessage_
{
  typedef ROCCurveMessage_<ContainerAllocator> Type;

  ROCCurveMessage_()
    : header()
    , team_name()
    , dataset_name()
    , dataset_idx(0)
    , source_points()
    , dest_points()
    , distances()  {
    }
  ROCCurveMessage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , team_name(_alloc)
    , dataset_name(_alloc)
    , dataset_idx(0)
    , source_points(_alloc)
    , dest_points(_alloc)
    , distances(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _team_name_type;
  _team_name_type team_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dataset_name_type;
  _dataset_name_type dataset_name;

   typedef uint8_t _dataset_idx_type;
  _dataset_idx_type dataset_idx;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _source_points_type;
  _source_points_type source_points;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _dest_points_type;
  _dest_points_type dest_points;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _distances_type;
  _distances_type distances;




  typedef boost::shared_ptr< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ROCCurveMessage_

typedef ::rvc_utils::ROCCurveMessage_<std::allocator<void> > ROCCurveMessage;

typedef boost::shared_ptr< ::rvc_utils::ROCCurveMessage > ROCCurveMessagePtr;
typedef boost::shared_ptr< ::rvc_utils::ROCCurveMessage const> ROCCurveMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rvc_utils::ROCCurveMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rvc_utils

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg'], 'rvc_utils': ['/home/viki/WurzelWorkspace/src/rvc_utils/msg'], 'geometry_msgs': ['/opt/ros/groovy/share/geometry_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63eb1174b4edca6e42f917226009d5e3";
  }

  static const char* value(const ::rvc_utils::ROCCurveMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63eb1174b4edca6eULL;
  static const uint64_t static_value2 = 0x42f917226009d5e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rvc_utils/ROCCurveMessage";
  }

  static const char* value(const ::rvc_utils::ROCCurveMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
# team name in RVC \n\
string team_name\n\
\n\
# name of the dataset (boat/bikes/graffiti)\n\
string dataset_name\n\
\n\
# index of the image in the dataset from which the destination points originate\n\
uint8 dataset_idx\n\
\n\
# the feature point positions in the source image\n\
geometry_msgs/Point32[] source_points\n\
\n\
# the corresponding fount mathces in the destination image\n\
geometry_msgs/Point32[] dest_points\n\
\n\
# descriptor distances of above matches\n\
float32[] distances\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::rvc_utils::ROCCurveMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.team_name);
      stream.next(m.dataset_name);
      stream.next(m.dataset_idx);
      stream.next(m.source_points);
      stream.next(m.dest_points);
      stream.next(m.distances);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ROCCurveMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rvc_utils::ROCCurveMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rvc_utils::ROCCurveMessage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "team_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.team_name);
    s << indent << "dataset_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dataset_name);
    s << indent << "dataset_idx: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dataset_idx);
    s << indent << "source_points[]" << std::endl;
    for (size_t i = 0; i < v.source_points.size(); ++i)
    {
      s << indent << "  source_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.source_points[i]);
    }
    s << indent << "dest_points[]" << std::endl;
    for (size_t i = 0; i < v.dest_points.size(); ++i)
    {
      s << indent << "  dest_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.dest_points[i]);
    }
    s << indent << "distances[]" << std::endl;
    for (size_t i = 0; i < v.distances.size(); ++i)
    {
      s << indent << "  distances[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.distances[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RVC_UTILS_MESSAGE_ROCCURVEMESSAGE_H
