multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_link
    child_frame_id: base_link
groups:
  - name: grappler
    base_link: grappler_base_link
    tip_link: grappler_wrist_link
default_collision_operations:
  - object1: base_link
    object2: grappler_base_link
    operation: disable  # Adjacent in collision
  - object1: grappler_base_link
    object2: grappler_shoulder_pan_link
    operation: disable  # Adjacent in collision
  - object1: grappler_shoulder_pan_link
    object2: grappler_shoulder_tilt_link
    operation: disable  # Adjacent in collision
  - object1: grappler_shoulder_tilt_link
    object2: grappler_arm_link
    operation: disable  # Adjacent in collision
  - object1: grappler_arm_link
    object2: grappler_forearm_link
    operation: disable  # Adjacent in collision
  - object1: grappler_forearm_link
    object2: grappler_wrist_link
    operation: disable  # Adjacent in collision
  - object1: grappler_wrist_link
    object2: grappler_finger01_link
    operation: disable  # Adjacent in collision
  - object1: grappler_wrist_link
    object2: grappler_finger02_link
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: grappler_shoulder_tilt_link
    operation: disable  # Never in collision
  - object1: grappler_finger01_link
    object2: grappler_finger02_link
    operation: disable  # Never in collision
  - object1: grappler_finger01_link
    object2: grappler_forearm_link
    operation: disable  # Never in collision
  - object1: grappler_finger02_link
    object2: grappler_forearm_link
    operation: disable  # Never in collision
  - object1: grappler_forearm_link
    object2: grappler_shoulder_tilt_link
    operation: disable  # Never in collision