<?xml version="1.0"?>
<robot>
  <include filename="$(find robotino_grappler_description)/urdf/grappler_hardware.xacro" />
  <material name="white">
    <color rgba="0.87 0.90 0.87 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  
  <macro name="grappler" params="parent *origin">
    <link name="grappler_base_link" />
	<joint name="grappler_base_joint" type="fixed">
	  <insert_block name="origin"/>
	  <parent link="${parent}"/>
	  <child link="grappler_base_link"/>
	</joint>
	
	<!-- Fake shoulder pan joint -->
	<link name="grappler_shoulder_pan_link" />
	<joint name="grappler_shoulder_pan_joint" type="continuous">
	  <origin xyz="0 0 ${SHOULDER_HEIGHT/2 + 0.075}" rpy="0 0 0"/>
	  <axis xyz="0 0 1"/>
	  <parent link="grappler_base_link"/>
	  <child link="grappler_shoulder_pan_link"/>
	</joint>
	
	<!-- Shoulder tilt joint -->
	<shoulder parent="grappler_shoulder_pan_link" name="grappler_shoulder_tilt" color="black">
	  <origin xyz="0.07 0 0"/>
	</shoulder>
	
	<!-- Arm joint -->
	<arm parent="grappler_shoulder_tilt_link" name="grappler_arm" color="white" vlimit="1.571" llimit="-2.617" ulimit="2.617">
	  <origin xyz="0 0 ${SHOULDER_HEIGHT/2 - OVERLAP_LARGE/2}" rpy="0 0 0"/>
	</arm>
	
	<!-- Forearm joint -->
	<forearm parent="grappler_arm_link" name="grappler_forearm" color="black" vlimit="1.571" llimit="-2.617" ulimit="2.617">
	  <origin xyz="0 0 ${ARM_HEIGHT}" rpy="0 0 0"/>
	</forearm>
	
	<!-- Wrist joint -->
	<wrist parent="grappler_forearm_link" name="grappler_wrist" color="white" vlimit="1.571" llimit="-2.617" ulimit="2.617">
	  <origin xyz="0 0 ${FOREARM_HEIGHT - OVERLAP_SMALL}" rpy="0 0 0"/>
	</wrist>
	
	<!-- Finger 01 join -->
	<finger01 parent="grappler_wrist_link" name="grappler_finger01" color="black" vlimit="1.571" llimit="0.0" ulimit="0.015">
	  <origin xyz="0.015 ${WRIST_WIDTH/2 - FINGER_WIDTH/2} ${WRIST_HEIGHT}" rpy="0 0 0"/>
	</finger01>
	
	<!-- Finger 02 join -->
	<finger02 parent="grappler_wrist_link" name="grappler_finger02" color="black" vlimit="1.571" llimit="-0.015" ulimit="0.0">
	  <origin xyz="0.015 ${-WRIST_WIDTH/2 + FINGER_WIDTH/2} ${WRIST_HEIGHT}" rpy="0 0 0"/>
	</finger02>
  </macro>
</robot>
